version: 1.0.{build}

environment:
  matrix:
    - ANDROID_HOME: "C:\\android-sdk"
      JAVA_HOME: "C:\\Program Files\\Java\\jdk17"

install:
  # 下载并安装Android SDK
  - appveyor DownloadFile https://dl.google.com/android/repository/commandlinetools-win-8512546_latest.zip
  - 7z x commandlinetools-win-8512546_latest.zip -o%ANDROID_HOME%
  - yes | %ANDROID_HOME%\\cmdline-tools\\bin\\sdkmanager.bat --sdk_root=%ANDROID_HOME% "platform-tools" "platforms;android-32" "build-tools;32.0.0"
  # 设置Gradle
  - set PATH=%PATH%;%ANDROID_HOME%\\platform-tools

build_script:
  - gradlew.bat assembleDebug

artifacts:
  - path: app\build\outputs\apk\debug\*.apk
    name: Debug APK

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
